const SHEET_ID='1boeKEkR0U2Kld3NwZNCBYXMG7agZEWRe';
const HEADERS={Lancamentos:['ID','Data do registro','Tipo de Lançamento','Tipo de Tanque','Tanque','Quantidade (kg)','Observação','Usuário','Atualizado em','Status'],Tanques:['ID','Tipo','Capacidade (kg)','Ativo','Atualizado em'],Usuarios:['ID','Nome','Perfil','Senha hash','Salt','Ativo','Atualizado em'],Auditoria:['Quando','Ação','ID','Usuário','Detalhes']};
function setup(){const ss=SpreadsheetApp.openById(SHEET_ID);Object.keys(HEADERS).forEach(n=>{let s=ss.getSheetByName(n)||ss.insertSheet(n);s.getRange(1,1,1,HEADERS[n].length).setValues([HEADERS[n]]);s.setFrozenRows(1);});let tanks=ss.getSheetByName('Tanques');if(tanks.getLastRow()<2)tanks.getRange(2,1,5,5).setValues([['UMB 1072','UMB',12000,true,new Date()],['UMB 1123','UMB',10500,true,new Date()],['EBE 1','EBE',42000,true,new Date()],['EBE 2','EBE',42000,true,new Date()],['EBE 3','EBE',42000,true,new Date()]]);return {ok:true}}
function doGet(){return out_({ok:true,action:'health',app:'Controle de Paiol',time:new Date()})}
function doPost(e){const p=JSON.parse(e.postData.contents||'{}');try{if(p.action==='snapshot')return out_(snapshot_());if(p.action==='record')return out_(record_(p));if(p.action==='update-record')return out_(update_(p));if(p.action==='delete-record')return out_(delete_(p));if(p.action==='sync')return out_(sync_(p.payload));return out_({ok:false,error:'Ação não reconhecida.'})}catch(err){return out_({ok:false,error:err.message})}}
function snapshot_(){const ss=SpreadsheetApp.openById(SHEET_ID);return {ok:true,tanks:rows_('Tanques'),records:rows_('Lancamentos'),users:rows_('Usuarios')}}
function rows_(n){const v=SpreadsheetApp.openById(SHEET_ID).getSheetByName(n).getDataRange().getValues();return v.slice(1).filter(r=>r[0]).map(r=>({id:r[0],date:r[1],type:r[2],category:r[3],tank:r[4],qty:r[5],note:r[6],user:r[7],updated:r[8],status:r[9]}))}
function record_(p){const s=SpreadsheetApp.openById(SHEET_ID).getSheetByName('Lancamentos');const id=Utilities.getUuid();s.appendRow([id,p.date,p.type,p.category,p.tank,Number(p.qty),p.note||'',p.user||'Operador',new Date(),'Ativo']);audit_('ENTRADA',id,p.user,p);return snapshot_()}
function update_(p){const s=SpreadsheetApp.openById(SHEET_ID),sh=s.getSheetByName('Lancamentos'),data=sh.getDataRange().getValues(),i=data.findIndex(r=>r[0]===p.id);if(i<1)throw Error('Lançamento não encontrado');sh.getRange(i+1,2,1,9).setValues([[p.date,p.type,p.category,p.tank,Number(p.qty),p.note||'',p.user||'Operador',new Date(),'Ativo']]);audit_('CORREÇÃO',p.id,p.user,p);return snapshot_()}
function delete_(p){const sh=SpreadsheetApp.openById(SHEET_ID).getSheetByName('Lancamentos'),data=sh.getDataRange().getValues(),i=data.findIndex(r=>r[0]===p.id);if(i<1)throw Error('Lançamento não encontrado');sh.getRange(i+1,10).setValue('Excluído');audit_('EXCLUSÃO',p.id,p.user,p);return snapshot_()}
function sync_(p){const lock=LockService.getScriptLock();lock.waitLock(15000);try{const ss=SpreadsheetApp.openById(SHEET_ID);p.tanks.forEach(t=>{});p.records.forEach(r=>{const existing=rows_('Lancamentos').find(x=>x.id===r.id);if(!existing)record_(r)});return snapshot_()}finally{lock.releaseLock()}}
function audit_(a,id,u,d){SpreadsheetApp.openById(SHEET_ID).getSheetByName('Auditoria').appendRow([new Date(),a,id,u||'',JSON.stringify(d)])}
function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
